export enum ERROR_CODE_ENUM {
  UNAUTHORIZED = "UNAUTHORIZED",
  ACCESS_DENIED = "ACCESS_DENIED",
  MISSING_TOKEN = "MISSING_TOKEN",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  UNEXPECTED_ERROR = "UNEXPECTED_ERROR",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  INVALID_EMAIL = "INVALID_EMAIL",
  NETWORK_ERROR = "NETWORK_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  CORS_ERROR = "CORS_ERROR",
  WEEK_PASSWORD = "WEEK_PASSWORD",
  INVALID_SESSION = "INVALID_SESSION",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
}

export type ERROR_CODE = keyof typeof ERROR_CODE_ENUM;

// List of all error code of Network
// Example: Request timeout, network error...
export const NETWRORK_ERROR_CODE = [
  500, 501, 502, 503, 504, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529,
  530,
];
